Controllers films users
MishaH9201/java-filmorate pull request #7
Opened 2022-06-10 08:20 UTC by MishaH9201

2022-06-10 14:41 UTC, Fleaman777 requested changes

2022-06-10 14:41 UTC, Fleaman777 commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
нужно донастроить .gitignore файл, что бы на гитхаб не попадали временные директории и файлы, такие как .idea и др.

2022-06-10 14:41 UTC, Fleaman777 commented on java-filmorate/src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if(error.hasErrors()){
если будет какая-та ошибка, мы о ней и так узнаем, 
+ лучше оставить оригинальную причину и не перебрасывать new ValidationException(), т.к. этот эксепшен тут будет немного не соответствовать
из аргументов можно тоже убрать,

2022-06-10 14:41 UTC, Fleaman777 commented on java-filmorate/src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public static Film valid(Film film,Map<Integer,Film> films){
для названия метода лучше использовать глагол, например можно так: validateFilm

2022-06-10 14:41 UTC, Fleaman777 commented on java-filmorate/src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        int id=0;
айдишник можно вынести в поле класса, 
а что бы его проинкрементировать, использовать для этого отдельным метод. 
а этот метод уже можно будет использовать для просечивания айди при создании фильма 

что-то похожее ты делал в таск менеджере

2022-06-10 14:41 UTC, Fleaman777 commented on java-filmorate/src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
к юзер контроллеру относятся все те же моменты, что и к фильмКотроллеру

2022-06-10 14:41 UTC, Fleaman777 commented on java-filmorate/src/main/java/ru/yandex/practicum/filmorate/exeption/ValidationException.java
> +public class ValidationException extends RuntimeException {
ValidationException можно наследовать от ResponseStatusException,
и потом использовать конструктор:

public ValidationException(HttpStatus status, String massage) {
super(status, massage);
}

где status какой-нибудь соответсвующий ошибке Http статус

2022-06-10 14:41 UTC, Fleaman777 commented on java-filmorate/src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        validator = factory.getValidator();
олтичное применение метода с аннотацией @BeforeAll

2022-06-10 14:41 UTC, Fleaman777 commented on java-filmorate/src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    public void shouldThrowsExceptionIfFilmNameIsEmpty() {
правильные названия тест-методов 👍🏼

2022-06-10 14:41 UTC, Fleaman777 commented on java-filmorate/src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +}
В enterprise приложениях на java, особенно написанных на Spring, в ....ControllerTest обычно тестируется api - на контроллер приходят определенные запросы(это делается специальной сущностью, а не просто вызывается эндпоинт метод), приложение полностью все отрабатывает, и затем отвечает определенным кодом и response body, которые и проверяются - такие тесты называются интеграционными.
Валидацию хорошо тестировать в обычных юнит тестах. Как раз, это будет проще сделать, если ее вынести в отдельный класс в отдельной директории.

этот комментарий тоже больше для информации,
если вдруг решишь часть валидации вынести в отдельный класс, можешь частично реализовать этот подход

2022-06-10 14:41 UTC, Fleaman777 commented on java-filmorate/src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public static User valid(User user, Map<Integer, User> users) {
возможно в нашем случае, и на данный момент, создание отдельного класса в котором будут лежать валидационные методы избыточно,

но более правильный подход тогда, когда контроллер только принимает запросы и отдает респонсы, а всю остальную логику выполняют другие классы(сервисы)

это не считается ошибкой,
выносить этот метод в отдельный класс или нет остается за тобой :)

аналагично и в фльм контроллере

2022-06-12 10:41 UTC, MishaH9201 commented
Изменения

2022-06-15 06:41 UTC, merged